#!/usr/bin/env bash
# secure-permissions.sh — Lock down queue/auth file permissions and configure
# logrotate for the journald + queue archive files.
#
# Idempotent: safe to re-run.
#
# Usage:
#   sudo bash secure-permissions.sh <agentname>
#
# Assumes the v1.2.0 layout (post install-service-user.sh):
#   App:   /opt/<agentname>
#   Auth:  /var/lib/<agentname>/whatsapp-auth
#   User:  openclaw-wa
#
# What it does:
#   1. chmod 0600 on every queue file (inbound, outbound, processed*, read-only-log).
#   2. chmod 0700 on queue/, auth/, and base dirs.
#   3. Installs /etc/logrotate.d/<agentname> rotating the archive JSONs daily,
#      keeping 7 days, compressing rotated files.
#
# What it does NOT do:
#   - Configure journald rotation (system-wide via /etc/systemd/journald.conf;
#     out of scope for a per-agent script).
#   - Encrypt files at rest (use LUKS at the disk level for that).

set -euo pipefail

AGENT="${1:-}"
if [ -z "$AGENT" ]; then
  echo "usage: sudo bash $0 <agentname>" >&2
  exit 2
fi

if [ "$EUID" -ne 0 ]; then
  echo "must run as root (sudo)" >&2
  exit 2
fi

SERVICE_USER="openclaw-wa"
APP_BASE="/opt/${AGENT}"
QUEUE_DIR="${APP_BASE}/queue"
AUTH_DIR="/var/lib/${AGENT}/whatsapp-auth"
LOGROTATE_FILE="/etc/logrotate.d/${AGENT}"

step() { echo ""; echo "=== $1 ==="; }

# ---------------------------------------------------------------------------
step "1. Tighten ownership"
if id "$SERVICE_USER" >/dev/null 2>&1; then
  if [ -d "$APP_BASE" ]; then
    chown -R "${SERVICE_USER}:${SERVICE_USER}" "$APP_BASE"
    echo "  $APP_BASE → ${SERVICE_USER}"
  else
    echo "  WARNING: $APP_BASE not found — run install-service-user.sh first" >&2
  fi
  if [ -d "$AUTH_DIR" ]; then
    chown -R "${SERVICE_USER}:${SERVICE_USER}" "$(dirname "$AUTH_DIR")"
    echo "  $AUTH_DIR → ${SERVICE_USER}"
  fi
else
  echo "  WARNING: user $SERVICE_USER does not exist — run install-service-user.sh first" >&2
fi

# ---------------------------------------------------------------------------
step "2. Tighten file permissions"
if [ -d "$APP_BASE" ]; then
  chmod 0700 "$APP_BASE"
fi
if [ -d "$QUEUE_DIR" ]; then
  chmod 0700 "$QUEUE_DIR"
  # All files in queue (JSONs containing message bodies) → 0600
  find "$QUEUE_DIR" -type f -exec chmod 0600 {} +
  echo "  $QUEUE_DIR/* → 0600"
fi
if [ -d "$AUTH_DIR" ]; then
  chmod 0700 "$(dirname "$AUTH_DIR")" "$AUTH_DIR"
  find "$AUTH_DIR" -type f -exec chmod 0600 {} + 2>/dev/null || true
  echo "  $AUTH_DIR/* → 0600"
fi

# ---------------------------------------------------------------------------
step "3. Install logrotate config"
cat > "$LOGROTATE_FILE" <<EOF
# Rotation for ${AGENT} WhatsApp agent queue archives.
# Generated by secure-permissions.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
${QUEUE_DIR}/processed.json
${QUEUE_DIR}/read-only-log.json
{
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su ${SERVICE_USER} ${SERVICE_USER}
    create 0600 ${SERVICE_USER} ${SERVICE_USER}
}
EOF
chmod 0644 "$LOGROTATE_FILE"
echo "  installed: $LOGROTATE_FILE"

# Validate
if logrotate -d "$LOGROTATE_FILE" >/dev/null 2>&1; then
  echo "  logrotate config valid"
else
  echo "  WARNING: logrotate -d failed — inspect manually: logrotate -d $LOGROTATE_FILE" >&2
fi

echo ""
echo "=========================================="
echo " Permissions hardened."
echo " Verify with:"
echo "   ls -la $QUEUE_DIR"
echo "   logrotate -d $LOGROTATE_FILE"
echo "=========================================="
